apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-app.fullname" . }}
data:
  APP_PORT: {{ .Values.service.containerPort | quote }}
  APP_ENVIRONMENT: {{ .Values.config.environment | quote }}
  APP_VERSION: {{ .Values.config.version | quote }}
