apiVersion: v1
kind: Service
metadata:
  name: cloud-native-java-app
spec:
  type: ClusterIP
  selector:
    app: cloud-native-java-app
  ports:
    - name: http
      port: 80
      targetPort: http
