replicaCount: 1
image:
  digest: "sha256:REPLACE_WITH_DEV_DIGEST"
config:
  environment: dev
  logLevel: DEBUG
  featureNewUi: "true"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
