apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-java-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-java-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-java-service
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
          # TODO: Add mandatory platform guardrails after policy confirmation.
