apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-java-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
