apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
data:
  APP_PORT: {{ .Values.containerPort | quote }}
  APP_ENVIRONMENT: {{ .Values.config.environment | quote }}
  APP_MESSAGE: {{ .Values.config.message | quote }}
