replicaCount: 4
image:
  digest: "sha256:REPLACE_WITH_PROD_DIGEST"
config:
  environment: prod
  logLevel: WARN
  featureNewUi: "false"
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi
