{
 "title": "Java App Centralized Logs",
 "tags": [
  "logging",
  "loki",
  "portfolio"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Recent application logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"java-app\", environment=\"learning\"}"
    }
   ]
  },
  {
   "title": "Log volume by level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({service=\"java-app\", environment=\"learning\"}[5m]))"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"java-app\", environment=\"learning\", level=\"ERROR\"}"
    }
   ]
  }
 ]
}