apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "java-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
