apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: microservices-order-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: inventory-service
          image: microservices-order/inventory-service:0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8081"
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests: {cpu: 50m, memory: 64Mi}
            limits: {cpu: 300m, memory: 192Mi}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: temporary-files
              mountPath: /tmp
      volumes:
        - name: temporary-files
          emptyDir:
            sizeLimit: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: microservices-order-demo
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 8081
      targetPort: http
