apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - order-configmap.yaml
  - inventory-service.yaml
  - payment-service.yaml
  - notification-service.yaml
  - order-service.yaml
