#!/usr/bin/env python3
"""Convert Terraform `ansible_hosts` output into an Ansible inventory.

This is the provisioning -> configuration handoff: Terraform emits one record per
node, and this script turns that JSON into a static Ansible inventory the
playbook can target. No cloud, no SSH, no secrets are involved.

Usage:
    # from a saved file (safe, no Terraform required):
    python3 scripts/generate-inventory.py \\
        examples/terraform-output/ansible_hosts.dev.json \\
        ansible/inventory.ini

    # straight from Terraform:
    terraform -chdir=terraform/environments/dev output -json ansible_hosts \\
        | python3 scripts/generate-inventory.py - ansible/inventory.ini

Arguments:
    input    Path to a JSON file, or "-" to read from stdin. Default: stdin.
    output   Path to write the inventory. Default: ansible/inventory.ini.

Options:
    --group NAME   Inventory group name to place hosts in (default: app).

The input JSON may be any of:
    * a bare list of host records (what `terraform output -json ansible_hosts`
      prints);
    * a wrapped output object {"value": [...], "type": ...};
    * the full `terraform output -json` object {"ansible_hosts": {"value": [...]}}.
Each host record must have at least a "name". "ansible_host", "ansible_user",
and "environment" are used when present.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def load_records(raw: str) -> list[dict]:
    """Parse the Terraform output JSON into a flat list of host records."""
    data = json.loads(raw)

    # Full `terraform output -json` object: pull the ansible_hosts output.
    if isinstance(data, dict) and "ansible_hosts" in data:
        data = data["ansible_hosts"]

    # A single wrapped output: {"value": [...], "type": ...}.
    if isinstance(data, dict) and "value" in data:
        data = data["value"]

    if not isinstance(data, list):
        raise ValueError(
            "Expected a list of host records (or a Terraform output wrapping one), "
            f"got {type(data).__name__}."
        )
    return data


def render_inventory(records: list[dict], group: str) -> str:
    """Render host records into Ansible ini-format inventory text."""
    lines: list[str] = []
    lines.append("# Generated by scripts/generate-inventory.py — do not edit by hand.")
    lines.append("# Regenerate from Terraform output; this file is git-ignored.")
    lines.append("")
    lines.append(f"[{group}]")

    environments = set()
    for rec in records:
        name = rec.get("name")
        if not name:
            raise ValueError(f"Host record is missing a 'name': {rec!r}")
        parts = [name]
        if rec.get("ansible_host"):
            parts.append(f"ansible_host={rec['ansible_host']}")
        if rec.get("ansible_user"):
            parts.append(f"ansible_user={rec['ansible_user']}")
        if rec.get("environment"):
            parts.append(f"environment={rec['environment']}")
            environments.add(rec["environment"])
        lines.append(" ".join(parts))

    lines.append("")
    lines.append(f"[{group}:vars]")
    # A generated inventory is per-environment; if all hosts agree, expose it as a
    # group var so the playbook/roles pick the right per-environment settings.
    if len(environments) == 1:
        lines.append(f"app_environment={environments.pop()}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert Terraform ansible_hosts output into an Ansible inventory."
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="-",
        help='JSON input file, or "-" for stdin (default: stdin).',
    )
    parser.add_argument(
        "output",
        nargs="?",
        default="ansible/inventory.ini",
        help="Inventory file to write (default: ansible/inventory.ini).",
    )
    parser.add_argument(
        "--group",
        default="app",
        help="Inventory group name for the hosts (default: app).",
    )
    args = parser.parse_args(argv)

    if args.input == "-":
        raw = sys.stdin.read()
    else:
        raw = Path(args.input).read_text(encoding="utf-8")

    try:
        records = load_records(raw)
    except (ValueError, json.JSONDecodeError) as exc:
        print(f"error: could not parse input: {exc}", file=sys.stderr)
        return 1

    if not records:
        print("error: no host records found in input.", file=sys.stderr)
        return 1

    try:
        inventory = render_inventory(records, args.group)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    out_path = Path(args.output)
    if out_path.parent and not out_path.parent.exists():
        out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(inventory, encoding="utf-8")

    print(f"Wrote {len(records)} host(s) to {out_path} (group [{args.group}]).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
