# DEV: minimal footprint, single replica.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-java-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
