apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
commonLabels:
  environment: dev
images:
  - name: my-cloud-native-java-app
    newTag: dev-placeholder
configMapGenerator:
  - name: app-config
    literals:
      - APP_ENVIRONMENT=dev
