{{- if .Values.ingress.enabled }}
# Rendering this resource still requires an installed Ingress controller to work.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "java-app.fullname" . }}
                port:
                  name: http
{{- end }}
